// ~~ Generated by projen. To modify, edit .projenrc.js and run "npx projen".
import * as path from 'path';
import * as lambda from 'aws-cdk-lib/aws-lambda';
import { Construct } from 'constructs';

/**
 * Props for SwaggerUiFunction
 */
export interface SwaggerUiFunctionProps extends lambda.FunctionOptions {
}

/**
 * An AWS Lambda function which executes src/swagger-ui.
 */
export class SwaggerUiFunction extends lambda.Function {
  constructor(scope: Construct, id: string, props?: SwaggerUiFunctionProps) {
    super(scope, id, {
      description: 'src/swagger-ui.lambda.ts',
      ...props,
      runtime: lambda.Runtime.NODEJS_14_X,
      handler: 'index.handler',
      code: lambda.Code.fromAsset(path.join(__dirname, '../assets/swagger-ui.lambda')),
    });
  }
}